CREATE TABLE prenotazioni (
	id INT PRIMARY KEY,
	who VARCHAR(250) NOT NULL,
	isSchoolHour BOOLEAN DEFAULT FALSE,
	approvata BOOLEAN DEFAULT FALSE,
	CONSTRAINT id_fk FOREIGN KEY(id) REFERENCES timetable(id) ON DELETE CASCADE
);